<h1>id: {{ $academicaprogram->id }}</h1>
<h3>names: {{ $academicaprogram->names }}</h3>
<h3>lastnames: {{ $academicaprogram->lastnames }}</h3>
<h3>email: {{ $academicaprogram->email }}</h3>
<h3>movil: {{ $academicaProgram->movil }}</h3>
<h3>doc_type: {{ $academicaProgram->doc_type }}</h3>
<h3>type: {{ $academicaProgram->type }}</h3>
<h3>project_id: {{ $academicaProgram->project_id }}</h3>
<h3>academic_program_id: {{ $academicaprogram->academic_program_id }}</h3>
<h3>users_id: {{ $academicaprogram->users_id }}</h3>